name: CI

on:
  push:
    branches:
      - '**/*'
      - '!main'

defaults:
  run:
    shell: pwsh

jobs:
  ci: 
    name: CI
    runs-on: Ubuntu-Latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"

      - name: Install Utilities
        run: sudo apt-get install -y hunspell hunspell-en-gb

      - name: Restore Project
        run: dotnet tool restore && dotnet restore
  
      - name: Check Code Formatting
        run: dotnet fantomas . --check

      - name: Run Spell Check
        run: bash ./ci/spellcheck.sh

      - name: Run Test Suite
        run: dotnet test
